name: EmbedScript
version: $version
author: shirokuro
description: Script embedder
load: STARTUP
loadbefore:
  - Vault
main: com.github.kuro46.embedscript.EmbedScriptPlugin
commands:
  esinteract:
    description: Operations for interact event.
    usage: "Usage: /<command> help"
    permission: embedscript.admin
  eswalk:
    description: Operations for walk event.
    usage: "Usage: /<command> help"
    permission: embedscript.admin
  embedscript:
    description: Main command.
    usage: "Usage: /<command> help"
    permission: embedscript.admin
    aliases:
      - es
  sbinteract:
    description: Operations for interact event. You can use ScriptBlock's script format.
    usage: "Usage: /<command> help"
    permission: embedscript.admin
  sbwalk:
    description: Operations for walk event. You can use ScriptBlock's script format.
    usage: "Usage: /<command> help"
    permission: embedscript.admin
permissions:
  embedscript.*:
    default: op
    description: EmbedScript main permission.
    children:
      embedscript.admin: true
  embedscript.admin:
    default: op
    description: EmbedScript administration permission.
